### ISSUE TITLE
Windows does not recognize the ethernet adapter

### ISSUE THREAD

**Issue by chuspepe79** [wismna/HackPi#1]
Hello,
I've been trying to make poisontap work on a raspberry pi zero and start with Sammy Kamkar's github. After having several problems I wrote to Samy and he told me that I had to try Hackpi. After following your tutorial to do the installation I have had the same problems as with the Samy version. In Windows 10 I recognize the device as a Serial Bus. In Windows 7 I recognized the device as an RNDIS Ethernet Gadget but did not install the driver. In linux I install the USB device but nothing is executed.
Thank you very much! Regards!

**Comment by wismna** [comment]
Strange. Was there any issue with the installation?
Do you have the poisontap and HackPi folders in /home/pi? 
Are the .sh files in those folders executable?
Could you give me the output of dmesg?

**Comment by Itega** [comment]
Hi, same issue here.
I had no issue during the installation, the folders are in my /home/pi and the files are executable.

pastebin : [dmesg output](http://pastebin.com/Cd4L3Wff)

**Comment by wismna** [comment]
Thanks for your input. From what I can see from the dmesg log, it seems like rc.local is not executed.
Could you post the contents of /etc/rc.local so that I can check if I made a mistake somewhere?

**Comment by Itega** [comment]
Here is my rc.local : [pastebin](http://pastebin.com/pxXpBZK9)
I'm using ethernet to micro USB to SSH into my PI it may change something for the dmesg command ?
(not using it to test HackPi)

**Comment by wismna** [comment]
Great! Glad to hear everything is working. I'll update the installation guide to reflect that.
