### ISSUE TITLE
will this work on win 7?

### ISSUE THREAD

**Issue by AddaxSoft** [wismna/HackPi#2]

**Comment by wismna** [comment]
Not 100% certain, but it should, though. I currently don't have a Windows 7 PC to test it on, but I may have one available soon. I'll let you know.

**Comment by wismna** [comment]
I just tried on a Windows 7 computer, and it works! (though it's slower than Windows 10 to recognise the device)

**Comment by xbing6** [comment]
Does your composite device "serial + rndis" work with Win10 or Win7, automatically installs RNDIS driver and serial driver??

As for CDC ACM driver on Windows, Win10 can auto-install serial driver, but we must manually install serial driver for Windows 7/8, (use and update linux-cdc-acm.inf depends on vid/pid).

**Comment by wismna** [comment]
Well, I didn't add the CDC ACM function to the RNDIS configuration because during my tests, Windows would not load the RNDIS driver in that case. It would only work with the CDC ECM configuration.
However, if this works for you, I'd be happy to hear about it!

**Comment by AddaxSoft** [comment]
can you please add more details on how did you get it to install automatically on Win 7?

**Comment by wismna** [comment]
Sure, what details do you need? Windows should recognize it and install it without you having to do anything. Is something not working?

**Comment by AddaxSoft** [comment]
this works like a charm now, but it assigns a random IP; what do I need to change?

**Comment by AddaxSoft** [comment]
it worked perfectly :) 
at first I thought we failed, but then I waited for the USB fingerprinting to work and it assigned the right driver!

**Comment by wismna** [comment]
Cool!

Yeah, there is a slight delay for the fingerprinting to work.
