### ISSUE TITLE
Issue after reboot

### ISSUE THREAD

**Issue by Axi57** [wismna/HackPi#3]
I followed the tutorial, and it work well. But after the reboot of my raspberry Pi 3 (the one I using for the configuration) I'm unable to connect to the ssh and my USB keyboard is not detected.

Someone can help ? 
Thanks you for reading this.

ps : I'm using Jessie Lite.

**Comment by wismna** [comment]
Hi. Did you plug HackPi on a Raspberry Pi 3, or did you install it on a Raspberry Pi 3?

**Comment by Axi57** [comment]
Hi thanks for your answer

In fact I've set up Hack PI on an SD card on my Pi3 in order plug that sd
on my PiZero after the configuration.
After using HackPi with my Pizero I've tried to plug my micro SD back in my
Pi3 for show the data I've catch up
but impossible to login. My Keyboard is not detected anymore.

2017-01-30 15:34 GMT+01:00 wismna <notifications@github.com>:

**Comment by wismna** [comment]
Ok, I see. The Pi3 can't boot correctly with that SD card, unfortunately, as it is tailored specifically for the PiZero (especially the USB and network configurations)
To read its contents, I would suggest taking the SD card out of the PiZero and put it directly in a laptop or computer with an SD Card reader (internal or external).

**Comment by domitor1927** [comment]
Hi use on raspberry pi zero. after i install all, i reboot and now dont accept the ssh conection. i put the sd card and file ssh are missing, i create but each time i start the raspberry they delete my file.

**Comment by wismna** [comment]
Hi. Could you please explain in a bit more details? What do you mean, "file ssh are missing" ? What files exactly are disappearing?

**Comment by domitor1927** [comment]
The file is confusing, the problem is that I can not connect to ssh anymore to the raspberry pi zero. what i have to do to access to them by ssh?

**Comment by wismna** [comment]
You copied everything where your're supposed to? Which file is confusing?
When you start HackPi, is it recognized by your OS? (which OS are you connecting it to?)
How did you connect via ssh before installing HackPi?

**Comment by domitor1927** [comment]
yes i have made all the steps. 
the hackpi are recognized. I use Windows 10.
i use extraputty to connect to ssh, before install hackpi.
now i can't connect to ssh.

**Comment by wismna** [comment]
Ok, that's strange. How did you connect before installing HackPi? Did you use raspberry.local?
When you plug it in, after waiting a little bit, Windows should connect to the new network interface, with the gateway IP 1.0.0.1. Is this working?

**Comment by hahnstep** [comment]
Hi sorry for asking is the /boot/ssh file still there ?

**Comment by domitor1927** [comment]
I have made all more one time, now work 5 stars. =) and yes work in all machine with windows 10

**Comment by wismna** [comment]
Ah cool, glad to hear about it!
